language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE kiosk;' -uroot

after_success:
  - ./after_success.sh


notifications:
  email:
  - herve.tchepannou@gmail.com
