language: java

jdk:
  - oraclejdk8

sudo:
  - required

services:
  - mysql

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS kiosk; CREATE DATABASE kiosk;' -uroot

script:
  - mvn clean install

after_success:
  - ./after_success.sh


notifications:
  email:
  - herve.tchepannou@gmail.com
