language: java
dist: trusty

jdk:
  - oraclejdk8

sudo:
  - required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS kiosk; CREATE DATABASE kiosk;' -uroot

#script:
#  - mvn clean install

after_success:
  - ./after_success.sh

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: "repository.tchepannou"
    skip_cleanup: true
    upload-dir: kiosk-api
    local_dir: target/deploy
    on:
      branch: master

  - provider: elasticbeanstalk
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    region: us-east-1
    app: kiosk-api
    env: kiosk-api-prod
    bucket_name: "repository.tchepannou"
    bucket_path: kiosk-api/kiosk-api.jar
    on:
      branch: master

notifications:
  email:
  - herve.tchepannou@gmail.com
