language: java
dist: trusty

jdk:
  - oraclejdk8

sudo:
  - required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS kiosk; CREATE DATABASE kiosk;' -uroot

#script:
#  - mvn clean install

after_success:
  - ./after_success.sh


notifications:
  email:
  - herve.tchepannou@gmail.com
