package com.tchepannou.kiosk.api.pipeline;

public interface PipelineConstants {
    String TOPIC_ARTICLE_SUBMITTED = "ARTICLE_SUBMITTED";
    String TOPIC_ARTICLE_CREATED = "ARTICLE_CREATED";
    String TOPIC_ARTICLE_CONTENT_EXTRACTED = "ARTICLE_CONTENT_EXTRACTED";
    String TOPIC_ARTICLE_IMAGE_EXTRACTED = "ARTICLE_IMAGE_EXTRACTED";
    String TOPIC_ARTICLE_REJECTED = "ARTICLE_REJECTED";
    String TOPIC_ARTICLE_VALIDATED = "ARTICLE_VALIDATED";

    String TOPIC_ARTICLE_PROCESS = "ARTICLE_PROCESS";

    String BEAN_RANKER_DIMENSIONS = "RANKER_DIMENSION";
    String BEAN_VALIDATOR_RULES = "VALIDATOR_RULES";
}
