package com.tchepannou.kiosk.api.pipeline;

public interface PipelineConstants {
    String TOPIC_ARTICLE_SUBMITTED = "ARTICLE_SUBMITTED";
    String TOPIC_ARTICLE_CREATED = "ARTICLE_CREATED";
    String TOPIC_ARTICLE_PROCESSED = "ARTICLE_PROCESSED";
    String TOPIC_ARTICLE_IMAGES_DOWNLOADED = "TOPIC_ARTICLE_IMAGES_DOWNLOADED";

    String TOPIC_IMAGE_SUBMITTED = "IMAGE_SUBMITTED";

    String TOPIC_PRINT = "PRINT";
}
